#pragma once

// include all subheaders
#include "ui/units.hpp"
#include "ui/element.hpp"
#include "ui/layer.hpp"
#include "ui/align.hpp"
#include "ui/solid.hpp"
#include "ui/panel.hpp"
#include "ui/image.hpp"
#include "ui/text.hpp"
#include "ui/pages.hpp"
#include "ui/drag.hpp"
#include "ui/camera.hpp"
#include "ui/textfield.hpp"
#include "ui/anim/easing.hpp"
#include "ui/anim/timer.hpp"
#include "ui/anim/setter.hpp"
#include "ui/anim/linear.hpp"
#include "ui/window.hpp"